version: '3.7'

services:

  psql:
    container_name: redose_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - redose_psql_data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d

  mailhog:
    container_name: redose_smtp
    image: cd2team/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  redose_psql_data:
